
[tox]
min_version = 4.0
isolated_build = true
env_list =
    py{310,311,312}-all
    py{310,311,312}-nogui
    py{310,311,312}-gui

[testenv]
description = Base env (default: run non-GUI tests)
extras = test
setenv =
    QT_QPA_PLATFORM = offscreen
    QT_LOGGING_RULES = qt.qpa.*=false
passenv =
    CI
    GITHUB_ACTIONS
    GITHUB_*
    USE_XVFB
commands =
    pytest -m "not gui" {posargs}

[testenv:py{310,311,312}-all]
description = Run full suite INCLUDING GUI tests
extras = test
setenv =
    QT_QPA_PLATFORM = offscreen
    QT_LOGGING_RULES = qt.qpa.*=false
passenv =
    CI
    GITHUB_ACTIONS
    GITHUB_*
    USE_XVFB
commands =
    pytest {posargs}

[testenv:py{310,311,312}-nogui]
description = Run everything EXCEPT GUI tests
extras = test
setenv =
    QT_QPA_PLATFORM = offscreen
    QT_LOGGING_RULES = qt.qpa.*=false
passenv =
    CI
    GITHUB_ACTIONS
    GITHUB_*
    USE_XVFB
commands =
    pytest -m "not gui" {posargs}

[testenv:py{310,311,312}-gui]
description = Run ONLY GUI tests
extras = test
setenv =
    QT_QPA_PLATFORM = offscreen
    QT_LOGGING_RULES = qt.qpa.*=false
passenv =
    CI
    GITHUB_ACTIONS
    GITHUB_*
    USE_XVFB
commands =
    pytest -m "gui" {posargs}
