name: pre-commit-format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre_commit_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - run: pip install pre-commit
      - run: pre-commit run --all-files
