name: Update pypi release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
      - master
    types:
      - labeled
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
          # we only use pyproject.toml for dependencies
          cache-dependency-path: |
            pyproject.toml

      - name: Install Qt/OpenGL runtime deps (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libopengl0 \
            libxkbcommon-x11-0 \
            libxcb-cursor0

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install "packaging>=24.2"
          pip install build
          pip install twine

      - name: Build and publish to PyPI
        if: ${{ github.event_name == 'push' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
        run: |
          python -m build
          ls dist/
          tar tvf dist/deeplabcut-live-gui-*.tar.gz
          python -m twine upload --verbose dist/*
